### ISSUE TITLE
期待出docker版的简易部署

### ISSUE THREAD

**Issue by justincnn** [wooveep/chatserver-web#1]

**Comment by slwl** [comment]
同样期待docker

**Comment by wooveep** [comment]
感谢关注！正在编写docker compose

**Comment by wooveep** [comment]
请参考项目中的  安装部署模块 @slwl  @justincnn  
https://github.com/wooveep/chatserver-web#%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2

**Comment by wooveep** [comment]
https://github.com/wooveep/chatserver-web#%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2
